#!/bin/bash

set -eo pipefail

ABBREV='<ABBREV>'

echo '###########################'
echo "BEGIN $ABBREV-user2 actions"
echo '###########################'

# Automatically run "LANG=en_US.UTF-8" at startup (needed for Ansible)
echo 'export LANG=en_US.UTF-8' >> /home/`whoami`/.bashrc

# BEGIN: activate NVM
export NVM_DIR="/home/`whoami`/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# END: activate NVM

# BEGIN: activate NVM at startup
echo 'export NVM_DIR="/home/`whoami`/.nvm"' >> /home/`whoami`/.bashrc
echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' >> /home/`whoami`/.bashrc
# END: activate NVM at startup

echo '--------------'
echo 'command -v nvm'
command -v nvm

echo '-------------'
echo 'nvm --version'
nvm --version

# BEGIN: install Node
echo '-----------------'
echo 'nvm install --lts'
nvm install --lts
# END: install Node

# BEGIN: activate Node at startup
# The commands to activate NVM at startup were automatically added during installation.
echo 'nvm use node' >> /home/`whoami`/.bashrc
# END: activate Node at startup

echo '-------'
echo 'node -v'
node -v

echo '-----------'
echo 'npm version'
npm version

echo '+++++++++++++++++++++'
echo 'BEGIN installing yarn'
echo '+++++++++++++++++++++'

echo '-----------------------'
echo 'npm install -g corepack'
npm install -g corepack

echo '------------'
echo 'yarn init -2'
yarn init -2

echo '-----------------------'
echo 'yarn set version stable'
yarn set version stable

echo '------------'
echo 'yarn install'
yarn install

echo '++++++++++++++++++++++++'
echo 'FINISHED installing yarn'
echo '++++++++++++++++++++++++'

echo '----------------------------'
echo 'sudo apt-get purge -y nodejs'
sudo apt-get purge -y nodejs

echo '##############################'
echo "FINISHED $ABBREV-user2 actions"
echo '##############################'
