#!/bin/bash

set -eo pipefail

echo '-------------------'
echo 'BEGIN finalize-user'
echo '-------------------'

DATE=`date +%Y_%m%d_%H%M_%S -u`
echo "Build Date: $DATE" >> /home/`whoami`/login-times.txt

echo "cat /home/`whoami`/login-times.txt"
cat /home/`whoami`/login-times.txt

echo '----------------------'
echo 'FINISHED finalize-user'
echo '----------------------'
